rideshare/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('', admin.site.urls),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('user/<int:id>/', views.profile, name='profile'),
    path('user/<int:id>/regisdriver/', views.regisdriver, name='regisdriver'),
    path('user/<int:id>/editinfo/', views.editinfo, name='editinfo'),
    path('user/<int:id>/changepassword/', views.changepassword, name='changepassword'),

    path('display/<int:id>/', views.display, name='display'),
    path('display/<int:id>/<int:rid>/delete/', views.delete, name='delete'),
    path('display/<int:id>/<int:rid>/', views.curtride, name='curtride'),
    path('display/<int:id>/<int:rid>/complete/', views.complete, name='complete'),
    path('display/<int:id>/findride/driver/', views.findridedriver, name='findridedriver'),
    path('display/<int:id>/<int:rid>/handledrive/', views.handledrive, name='handledrive'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:id>/newride/', views.newride, name='newride'),
    path('<int:id>/newshare/', views.newshare, name='newshare'),
    path('<int:id>/<int:rid>/<int:passenger>/joinshare/', views.joinshare, name='joinshare'),
    path('<int:id>/<int:rid>/deleteshare/', views.deleteshare, name='deleteshare'),
    path('<int:id>/<int:rid>/editshare/', views.editshare, name='editshare')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.postgres.fields import ArrayField
from datetime import timedelta, datetime

def emptylist():
    return [];

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    #email and name in User
    driver = models.BooleanField(default=False)
    vehicle = models.CharField(max_length=20, blank=True)
    plate = models.CharField(max_length=10, blank=True)
    capacity = models.IntegerField(default=1, validators=[MaxValueValidator(200),MinValueValidator(1)])
    special = models.CharField(max_length=200, blank=True, default='')
    
class Ride(models.Model):
    status = models.CharField(max_length=10, default='open')
    destination = models.CharField(max_length=50, blank=False)
    arrivaldate = models.DateTimeField()
    passenger = models.IntegerField(validators=[MaxValueValidator(200),MinValueValidator(1)])
    sharable = models.BooleanField(default=False)
    vehicle = models.CharField(max_length=20, blank=True)
    special = models.CharField(max_length=200, blank=True)
    driver_id = models.IntegerField(default=-1, blank=True)
    rider_id = models.IntegerField(default=-1, blank=False)
    sharer_id = ArrayField(models.IntegerField(), default=emptylist)
    sharer_passenger = ArrayField(models.IntegerField(), default=emptylist)
    total_psg = models.IntegerField(validators=[MaxValueValidator(200),MinValueValidator(1)], default=0)

users/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .models import UserProfile, Ride
from django.contrib import auth
from .forms import RegistrationForm, LoginForm, DriverForm, RideForm, RideEditForm, ShareForm, PasswordForm, ShareEditForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.mail import send_mail


# homepage before login
def homepage(request):
    return render(request, 'users/homepage.html')

# logout your account
@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('users:homepage'))

# register a new account
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password2']

            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, password=password, email=email)

            user_profile = UserProfile(user=user)
            user_profile.save()

            return HttpResponseRedirect("/users/login/")

    else:
        form = RegistrationForm()

    return render(request, 'users/registration.html', {'form':form})

# login into your account
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('users:profile', args=[user.id]))
            else:
                return render(request, 'users/login.html', {'form':form, 'message': 'Wrong password. Please try again.'})

    else:
        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})

# profile info page
@login_required
def profile(request, id):
    user = get_object_or_404(User, id=id)
    user_profile = get_object_or_404(UserProfile, user=user)
    
    return render(request, 'users/profile.html', {'user': user, 'user_profile':user_profile})

# register as a driver
@login_required
def regisdriver(request, id):
    user = get_object_or_404(User, id=id)
    user_profile = get_object_or_404(UserProfile, user=user)

    if request.method == 'POST':
        form = DriverForm(request.POST)

        if form.is_valid():
            # driver update
            user_profile.driver = True
            user_profile.vehicle = form.cleaned_data['vehicle']
            user_profile.plate = form.cleaned_data['plate']
            user_profile.capacity = form.cleaned_data['capacity']
            user_profile.special = form.cleaned_data['special']
            user_profile.save()

            return HttpResponseRedirect(reverse('users:profile', args=[user.id]))

    else:
        form = DriverForm()

    return render(request, 'users/regisdriver.html', {'form': form, 'user': user})

# main user page, display rides info
@login_required
def display(request, id):
    user = get_object_or_404(User, id=id)
    user_profile = get_object_or_404(UserProfile, user=user)

    # rider
    # open rides
    queryset1 = Ride.objects.filter(status='open', rider_id=id)
    openrides_temp = list(queryset1)
    openrides = []
    for one in openrides_temp:
        temp_sharers = []
        for i in range(0, len(one.sharer_id)):
            curt_sharer = get_object_or_404(User, id=one.sharer_id[i]).first_name
            curt_psg = one.sharer_passenger[i]
            temp_sharers.append({'name': curt_sharer, 'num': curt_psg})
        openrides.append({'destination': one.destination, 'arrivaldate': one.arrivaldate, 'sharers': temp_sharers, 'id': one.id, 'group': len(one.sharer_id)})

    # confirmed rides
    queryset2 = Ride.objects.filter(status='confirmed', rider_id=id)
    confirmedrides = list(queryset2)
    cfm_info_rider = []
    for i in range(0, len(confirmedrides)):
        # get driver info
        curt_driver_id = confirmedrides[i].driver_id
        curt_driver = get_object_or_404(User, id=curt_driver_id)
        driver_name = curt_driver.first_name
        vehicle_info = get_object_or_404(UserProfile, user=curt_driver).vehicle
        curt_destination = confirmedrides[i].destination
        curt_arrivaldate = confirmedrides[i].arrivaldate
        # get sharer info
        temp_sharers = []
        for j in range(0, len(confirmedrides[i].sharer_id)):
            curt_sharer = get_object_or_404(User, id=confirmedrides[i].sharer_id[j]).first_name
            curt_psg = confirmedrides[i].sharer_passenger[j]
            temp_sharers.append({'name': curt_sharer, 'num': curt_psg})
        cfm_info_rider.append({'destination': curt_destination, 'arrivaldate': curt_arrivaldate, 'driver_name': driver_name, 'vehicle_info': vehicle_info, 'sharers': temp_sharers, 'id': confirmedrides[i].id, 'group': len(confirmedrides[i].sharer_id)})

    # driver
    queryset3 = Ride.objects.filter(~Q(status='complete'), driver_id=id)
    drive = list(queryset3)
    # if has current drive
    has_drive = len(drive) > 0
    owner = ''
    sharers = []
    if has_drive:
        drive = drive[0]
        owner = get_object_or_404(User, id=drive.rider_id).first_name
        for i in range(0, len(drive.sharer_id)):
            curt_share_id = drive.sharer_id[i]
            name = get_object_or_404(User, id=curt_share_id).first_name
            num_psg = drive.sharer_passenger[i]
            curt_sharer = {'name': name, 'num': num_psg}
            sharers.append(curt_sharer)

    # share
    # unconfirmed
    queryset4 = Ride.objects.filter(status='open')
    tempopenshare = list(queryset4)
    openshares = []
    for one in tempopenshare:
        if id in one.sharer_id:
            openshares.append(one)

    # confirmed
    queryset5 = Ride.objects.filter(status='confirmed')
    tempconfirmedshare = list(queryset5)
    confirmedshares = []
    for one in tempconfirmedshare:
        if id in one.sharer_id:
            curt_rider_id = one.rider_id
            rider_name = get_object_or_404(User, id=curt_rider_id).first_name
            curt_driver_id = one.driver_id
            curt_driver = get_object_or_404(User, id=curt_driver_id)
            driver_name = curt_driver.first_name
            vehicle_info = get_object_or_404(UserProfile, user=curt_driver).vehicle
            confirmedshares.append({'rider_name': rider_name, 'destination': one.destination, 'arrivaldate': one.arrivaldate, 'driver_name': driver_name, 'vehicle_info': vehicle_info})

    context = {
        'user': user,
        'user_profile': user_profile,
        'has_drive': has_drive,
        'drive': drive,
        'openrides': openrides,
        'cfm_info_rider': cfm_info_rider,
        'openshares': openshares,
        'confirmedshares': confirmedshares,
        'owner': owner,
        'sharers': sharers
    }
    return render(request, 'users/display.html', context)

# start a new ride as rider
@login_required
def newride(request, id):
    user = get_object_or_404(User, id=id)

    if request.method == 'POST':
        form = RideForm(request.POST)

        if form.is_valid():
            # status default open
            destination = form.cleaned_data['destination']
            arrivaldate = form.cleaned_data['arrivaldate']
            passenger = form.cleaned_data['passenger']
            sharable = form.cleaned_data['sharable']
            vehicle = form.cleaned_data['vehicle']
            special = form.cleaned_data['special']
            rider_id = id

            ride = Ride(destination=destination, arrivaldate=arrivaldate, passenger=passenger, sharable=sharable, vehicle=vehicle, special=special, rider_id=rider_id)
            ride.save()

            return HttpResponseRedirect(reverse('users:display', args=[id]))
    else:
        form = RideForm()
    return render(request, 'users/newride.html', {'form': form, 'user': user})

# edit current ride for rider
@login_required
def curtride(request, id, rid):
    user = get_object_or_404(User, id=id)
    user_profile = get_object_or_404(UserProfile, user=user)
    ride = get_object_or_404(Ride, id=rid)

    # prevent race
    if ride.status == 'open':
        if request.method == 'POST':
            form = RideEditForm(request.POST)
            if form.is_valid():
                # status default open
                ride.destination = form.cleaned_data['destination']
                ride.arrivaldate = form.cleaned_data['arrivaldate']
                ride.passenger = form.cleaned_data['passenger']
                ride.vehicle = form.cleaned_data['vehicle']
                ride.special = form.cleaned_data['special']

                ride.save()
                return HttpResponseRedirect(reverse('users:display', args=[user.id]))
        else:
            defaultData = {
                'destination': ride.destination,
                'arrivaldate': ride.arrivaldate,
                'passenger': ride.passenger,
                'vehicle': ride.vehicle,
                'special': ride.special
            }
            form = RideEditForm(defaultData)
        return render(request, 'users/curtride.html', {'user': user, 'user_profile': user_profile, 'form': form})
    else:
        return HttpResponseRedirect(reverse('users:display', args=[id]))

# driver clicked confirmed
@login_required
def complete(request, id, rid):
    ride = get_object_or_404(Ride, id=rid)
    if ride.status is not 'complete':
        ride.status = 'complete'
        ride.save()

users/templates/users/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Change Password</title>
</head>
<body>
    {% block content %}
    <h4>Account Info</h4>
    <ul>
        <li>Username: {{ user.username }}</li>
        <li>Email: {{ user.email }}</li>
    </ul>

    {% if message %}
    {{ message }}
    {% endif %}

    <h2>Password Change</h2>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="Submit Change"></div>
        </form>
        <a href="{% url 'users:profile' user.id%}">Back to profile</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/curtride.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Ride</title>
</head>
<body>
    {% block content %}
    <h2>Please edit the information about your ride</h2>
    <br>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="Submit Edit"></div>
        </form>
        <a href="{% url 'users:display' user.id %}">Back to display</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rides</title>
</head>
<body>
    {% block content %}
    {% if not user_profile.driver %}
    <a href="{% url 'users:regisdriver' user.id %}">Register for driver now!</a>
    {% endif %}
    <a href="{% url 'users:logout' %}">Log out</a>
    <a href="{% url 'users:profile' user.id %}">Account Info</a>
    <h4>Hi {{ user.first_name }}, welcomes!</h4>
    
    <!-- Info for the rider part -->
    {% if openrides|length > 0 %}
    <ul>Here are your unconfirmed rides as main rider:
        {% for ride in openrides %}
        <li>
            <a href="{% url 'users:curtride' user.id ride.id %}">To {{ ride.destination }} before {{ ride.arrivaldate }}</a>
            {% if ride.sharers|length > 0 %}
            <p>You have {{ ride.group }} group(s) of sharer</p>
            {% for s in ride.sharers %}
            <p>Sharer name: {{ s.name }}, passengers: {{ s.num }}</p>
            {% endfor %}
            {% else %}
            <p>This ride has no share riders.</p>
            {% endif %}
            <p>Delete this ride? <a href="{% url 'users:delete' user.id ride.id %}">Yes</a></p>
            <br>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if cfm_info_rider|length > 0 %}
    <ul>Here are your confirmed rides as main rider:
        {% for ride in cfm_info_rider %}
        <li>
            <p>Driver : {{ ride.driver_name }}</p>
            <p>And vehicle type: {{ ride.vehicle_info }}</p>
            <p>To {{ ride.destination }} before {{ ride.arrivaldate }}</p>
            {% if ride.sharers|length > 0 %}
            <p>You have {{ ride.group }} group(s) of sharer</p>
            {% for s in ride.sharers %}
            <p>Sharer name: {{ s.name }}, passengers: {{ s.num }}</p>
            {% endfor %}
            {% else %}
            <p>This ride has no share riders.</p>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <br>

    <!-- Info for the sharer part -->

    {% if openshares|length > 0 %}
    <ul>Here are your unconfirmed rides as sharer:
        {% for ride in openshares %}
        <li>
            <a href="{% url 'users:editshare' user.id ride.id %}">To {{ ride.destination }} before {{ ride.arrivaldate }}</a>
            <p>Do not want to exit this ride? <a href="{% url 'users:deleteshare' user.id ride.id %}">Yes</a></p>
            <br>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    {% if confirmedshares|length > 0 %}
    <ul>Here are your confirmed rides as sharer:
        {% for ride in confirmedshares %}
        <li>
            <p>Driver : {{ ride.driver_name }}</p>
            <p>And vehicle type: {{ ride.vehicle_info }}</p>
            <p>To {{ ride.destination }} before {{ ride.arrivaldate }}</p>
            <p>You are sharing this ride with main rider: {{ ride.rider_name }}</p>
            <br>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <br>

    <!-- Info for the driver part -->
    {% if user_profile.driver %}
    {% if has_drive %}
    <h4>And here's your drive info as a driver:</h4>
    <p>Your drive to {{ drive.destination }} is going on!<a href="{% url 'users:complete' user.id drive.id %}">complete</a></p>
    <p>More info:</p>
    <p>Current main rider: {{ owner }} of {{ drive.passenger }} people</p>
    {% if sharers|length > 0 %}
    <ul>
    {% for share in sharers %}
        <li>
            <p>Name of sharer: {{ share.name }}</p>
            <p>Number of this share group: {{ share.num }}</p>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <p>This is ride has no sharer yet.</p>
    {% endif %}
    {% else %}
    <a href="{% url 'users:findridedriver' user.id %}">Find a new ride as driver!</a>
    {% endif %}
    {% endif %}
    <br>

    <a href="{% url 'users:newride' user.id %}">Start a new ride now!</a>
    <p>or</p>
    <a href="{% url 'users:newshare' user.id %}">Join a ride with other riders!</a>
    {% endblock %}
</body>
</html>

users/templates/users/editinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Driver Info Edit</title>
</head>
<body>
    {% block content %}
    <h4>Account Info</h4>
    <ul>
        <li>Username: {{ user.username }}</li>
        <li>Email: {{ user.email }}</li>
    </ul>

    <h2>Driver Information</h2>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="Submit Change"></div>
        </form>
        <a href="{% url 'users:profile' user.id%}">Back to profile</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/editshare.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Share</title>
</head>
<body>
    {% block content %}
    <h2>Please edit the information about your shar ride</h2>
    <br>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="Submit Edit"></div>
        </form>
        <a href="{% url 'users:display' user.id %}">Back to display</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/findridedriver.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Find Available Ride to Drive</title>
</head>
<body>
    {% block content %}
    <a href="{% url 'users:logout' %}">Log out</a>
    <h4>Hi {{ user.first_name }}, welcomes!</h4>
    <ul>Here are rides available for you to choose:
        {% for ride in rides %}
        <li>
            <p>To {{ ride.destination }} before {{ ride.arrivaldate }}</p>
            <p>Passenger number: {{ ride.total_psg }}</p>
            <a href="{% url 'users:handledrive' user.id ride.id %}">Go for this one!</a>
        </li>
        <br>
        {% endfor %}
    </ul>
    <br>
    <a href="{% url 'users:display' user.id %}">Back</a>
    {% endblock %}
</body>
</html>

users/templates/users/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    {% block content %}
    <h1>Welcome to ride share HSs!</h1>
    <a href="{% url 'users:register' %}">Register an account now!</a>
    <a href="{% url 'users:login' %}">Login</a>
    {% endblock %}
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% block content %}

    <h2>Login</h2>

    {% if message %}
    {{ message }}
    {% endif %}

    {% if next %}
    <p>Hey, you cannot access that page.</p>
    {% endif %}

    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="field-wrapper">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="button-wrapper submit">
                    <p><input type="submit" value="Login"></p>
            </div>
        </form>
        <a href="/users/register/">Register</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/newride.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NewRide</title>
</head>
<body>
    {% block content %}
    <h2>Please fill the information about your ride</h2>
    <br>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="New Ride Begin!"></div>
        </form>
        <a href="{% url 'users:display' user.id%}">Back to display</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/newshare.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Share Ride</title>
</head>
<body>
    {% block content %}
    <h2>Please fill the information about your share ride</h2>
    <br>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="Find a share ride!"></div>
        </form>
        <a href="{% url 'users:display' user.id %}">Back to display</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>
    {% block content %}
    <h2>Account Info</h2>
    <ul>
        <li>Username: {{ user.username }}</li>
        <li>Email: {{ user.email }}</li>
    </ul>

    <h2>My Profile</h2>
    <ul>
        <li>First Name: {{ user.first_name }}</li>
        <li>Last Name: {{ user.last_name }}</li>
        {% if user_profile.driver %}
        <p>Here's your vehicle info:</p>
        <li>Vehicle Type: {{ user_profile.vehicle }}</li>
        <li>Plate Number: {{ user_profile.plate }}</li>
        <li>Passenget Capacity: {{ user_profile.capacity }}</li>
        {% if user_profile.special %}
        <li>Special Info: {{ user_profile.special}}</li>
        {% endif %}
        {% else %}
        <p>You are not a driver yet.</p>
        {% endif %}

        {% if user.is_authenticated %}
        {% if not user_profile.driver %}
        <a href="{% url 'users:regisdriver' user.id %}">Register for driver!</a>
        {% else %}
        <a href="{% url 'users:editinfo' user.id %}">Edit Your Driver info</a>
        {% endif %}
        
        <a href="{% url 'users:changepassword' user.id %}">Change Password</a>
        <a href="{% url 'users:display' user.id %}">Home</a>
        <a href="{% url 'users:logout' %}">Log out</a>
        {% endif %}
    </ul>

    {% endblock %}
</body>
</html>

users/templates/users/regisdriver.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DriverRegistration</title>
</head>
<body>
    {% block content %}
    <h2>Welcome to join us!</h2>

    <h4>Account Info</h4>
    <ul>
        <li>Username: {{ user.username }}</li>
        <li>Email: {{ user.email }}</li>
    </ul>

    <h2>Driver Information</h2>
    <div class="form-wrapper">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    {{ field.help_text|safe }}
                {% endif %}
            </div>
            {% endfor %}
            <div class="button-wrapper submit"><input type="submit" value="DriverRegister"></div>
        </form>
        <a href="{% url 'users:profile' user.id%}">Back to profile</a>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    {% block content %}
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper">
                    {{ field.errors }}
                    {{ field.label_tag}} {{ field }}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <input type="submit" value="Submit">
        </form>
    </div>
    {% endblock %}
</body>
</html>

users/templates/users/shareresult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Available Share Rides</title>
</head>
<body>
    {% block content %}
    <a href="{% url 'users:logout' %}">Log out</a>
    <h4>Hi {{ user.first_name }}, welcomes!</h4>

    {% if sharerides|length > 0 %}
    <ul>Here are sharable rides you can join:
        {% for ride in sharerides %}
        <li>
            <p>To {{ ride.destination }} before {{ ride.arrivaldate }}</p>
	    <a href="{% url 'users:joinshare' user.id ride.id passenger %}">join this ride</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No rides available for you to share now</p>
    <a href="{% url 'users:display' user.id %}">Back to display</a>
    {% endif %}

    {% endblock %}
</body>
</html>